"""
Many-body perturbation theory: Rayleigh-Schrodinger and Brillouin-Wigner.

Companion code to chapter 9 of *Quantum mechanics for Many-particle Systems*.

Everything is done in the determinant basis of chapter 5, where the
unperturbed Hamiltonian is diagonal and the perturbation is the rest of the
matrix.  Writing R = Q / (W_0 - H_0) for the resolvent, the Rayleigh-
Schrodinger series is generated by the standard recursion

    psi^(n)   = R [ V psi^(n-1) - sum_{k=1}^{n-1} E^(k) psi^(n-k) ] ,
    E^(n+1)   = <Phi_0| V |psi^(n)> ,

which reproduces the explicit first, second and third order expressions of
the text and continues to any order.  Brillouin-Wigner uses the exact energy
in the denominator instead and is solved self-consistently; its full
resummation is exact and reproduces the configuration-interaction energy.

Four models are treated, all of them met earlier in the book:

    pairing            chapters 4 and 5
    Lipkin             chapters 4, 6 and 7
    Hubbard            chapters 4 and 5
    pairing + p-h      chapter 7

and the size-extensivity test uses the two non-interacting copies of
chapter 5.

    Partition          -- H_0 either one-body (Moller-Plesset-like) or the
                          full diagonal (Epstein-Nesbet)
    rayleigh_schrodinger -- the series to any order
    brillouin_wigner   -- solved self-consistently, at a given order
    brillouin_wigner_exact -- the full resummation, which is exact

Author: Morten Hjorth-Jensen
"""

from math import comb

import numpy as np

import fci
import hartreefock as hfm
import rpa as rpamod


# ---------------------------------------------------------------------------
#  The partition of the Hamiltonian
# ---------------------------------------------------------------------------
class Partition:
    """A Hamiltonian matrix split as H = H_0 + V with H_0 diagonal.

    The reference determinant is the one from which the perturbation series
    is built; W_0 is its unperturbed energy.  Two choices of H_0 are offered:

    ``one_body``      H_0 is the one-body part, so that <Phi_0|V|Phi_0> is
                      non-zero and appears as the first-order energy.  This
                      is the partition used in the text.

    ``diagonal``      H_0 is the entire diagonal of H, so that the first-order
                      energy vanishes identically and every denominator is a
                      difference of full diagonal energies.  This is the
                      Epstein-Nesbet partition.
    """

    def __init__(self, H, h0_diagonal, reference, scheme="one_body"):
        self.H = np.asarray(H, dtype=float)
        self.dim = self.H.shape[0]
        self.reference = reference
        self.scheme = scheme
        if scheme == "one_body":
            self.w = np.asarray(h0_diagonal, dtype=float)
        elif scheme == "diagonal":
            self.w = np.diag(self.H).copy()
        else:
            raise ValueError(f"unknown scheme {scheme!r}")
        self.V = self.H - np.diag(self.w)
        self.w0 = float(self.w[reference])

        # the resolvent R = Q / (W_0 - H_0), zero on the reference
        denominator = self.w0 - self.w
        self.resolvent = np.zeros(self.dim)
        mask = np.arange(self.dim) != reference
        if np.any(np.abs(denominator[mask]) < 1e-12):
            raise ValueError("degenerate denominator: the reference is not "
                             "isolated in H_0")
        self.resolvent[mask] = 1.0 / denominator[mask]

    # ------------------------------------------------------------------
    @property
    def reference_energy(self):
        """W_0 + <Phi_0|V|Phi_0>, the energy through first order."""
        return self.w0 + float(self.V[self.reference, self.reference])

    def exact(self):
        return float(np.linalg.eigvalsh(self.H)[0])


# ---------------------------------------------------------------------------
#  Rayleigh-Schrodinger
# ---------------------------------------------------------------------------
def rayleigh_schrodinger(partition, order=3):
    """The RS energy corrections Delta E^(1) ... Delta E^(order).

    Uses the recursion quoted in the module docstring.  The returned list is
    indexed from one: ``energies[0]`` is Delta E^(1).
    """
    V, R, ref = partition.V, partition.resolvent, partition.reference
    psi0 = np.zeros(partition.dim)
    psi0[ref] = 1.0

    energies = [float(psi0 @ (V @ psi0))]          # Delta E^(1)
    psis = []                                       # psi^(1), psi^(2), ...
    for n in range(1, order):
        previous = psis[-1] if psis else psi0
        rhs = V @ previous
        for k in range(1, n):
            rhs = rhs - energies[k - 1] * psis[n - k - 1]
        psi_n = R * rhs
        psis.append(psi_n)
        energies.append(float(psi0 @ (V @ psi_n)))
    return energies


def rs_explicit(partition):
    """Delta E^(1,2,3) written out term by term, as a cross-check.

    The three expressions are

        E1 = V_00 ,
        E2 = sum_{m/=0} V_0m V_m0 / (W_0 - W_m) ,
        E3 = sum_{m,n/=0} V_0m V_mn V_n0 / [(W_0 - W_m)(W_0 - W_n)]
             - V_00 sum_{m/=0} V_0m V_m0 / (W_0 - W_m)^2 ,

    the second term of E3 being the renormalisation that removes the
    unlinked contribution.
    """
    V, R, ref = partition.V, partition.resolvent, partition.reference
    v0 = V[ref].copy()
    e1 = float(V[ref, ref])
    e2 = float(np.sum(v0 * R * v0))
    principal = float((v0 * R) @ (V @ (R * v0)))
    renormalisation = e1 * float(np.sum(v0 * R * R * v0))
    return e1, e2, principal - renormalisation, principal, renormalisation


# ---------------------------------------------------------------------------
#  Brillouin-Wigner
# ---------------------------------------------------------------------------
def brillouin_wigner(partition, order=2, max_iter=500, tol=1e-13):
    """Brillouin-Wigner to a given order, solved self-consistently.

    The denominators contain the exact energy E = W_0 + Delta E, so the
    equation must be iterated.  There is no renormalisation term at any
    order: that is the defining difference from Rayleigh-Schrodinger, and
    it is also why the result is not size extensive.
    """
    V, ref = partition.V, partition.reference
    v0 = V[ref].copy()
    mask = np.arange(partition.dim) != ref
    delta = 0.0
    for iteration in range(1, max_iter + 1):
        energy = partition.w0 + delta
        denominator = energy - partition.w
        if np.any(np.abs(denominator[mask]) < 1e-12):
            return np.nan, iteration
        r = np.zeros(partition.dim)
        r[mask] = 1.0 / denominator[mask]

        new = float(V[ref, ref])
        if order >= 2:
            new += float(np.sum(v0 * r * v0))
        if order >= 3:
            new += float((v0 * r) @ (V @ (r * v0)))
        if abs(new - delta) < tol:
            return new, iteration
        delta = new
    return delta, max_iter


def brillouin_wigner_exact(partition, max_iter=2000, tol=1e-13,
                           mixing=0.5):
    """The full Brillouin-Wigner resummation,

        Delta E = <Phi_0| V + V Q [E - H_0 - Q V Q]^(-1) Q V |Phi_0> ,

    which is not an approximation at all: solved self-consistently it
    reproduces the exact ground-state energy.

    The fixed-point map is not a contraction at strong coupling -- the
    right-hand side has poles at the eigenvalues of Q H Q -- so the
    iteration is damped, and we start from a value safely below the
    lowest of those poles so that the iteration approaches the physical
    root from the correct side.
    """
    V, ref = partition.V, partition.reference
    keep = np.arange(partition.dim) != ref
    v0 = V[ref, keep]
    Vqq = V[np.ix_(keep, keep)]
    w_q = partition.w[keep]
    # the poles of the resolvent are the eigenvalues of Q H Q
    poles = np.linalg.eigvalsh(np.diag(w_q) + Vqq)
    delta = poles[0] - partition.w0 - 1.0
    for iteration in range(1, max_iter + 1):
        energy = partition.w0 + delta
        M = np.diag(energy - w_q) - Vqq
        new = float(V[ref, ref] + v0 @ np.linalg.solve(M, v0))
        if abs(new - delta) < tol:
            return new, iteration
        delta = (1.0 - mixing) * delta + mixing * new
    return delta, max_iter


# ---------------------------------------------------------------------------
#  The models, all of them met earlier in the book
# ---------------------------------------------------------------------------
def pairing_partition(levels=4, particles=4, g=1.0, xi=1.0, scheme="one_body"):
    """The pairing model of chapters 4 and 5, in the full determinant space."""
    model = fci.PairingFCI(levels=levels, n_particles=particles, g=g, xi=xi)
    H = model.matrix()
    w = np.array([sum(xi * (o // 2) for o in range(model.basis.n_orbitals)
                      if (s >> o) & 1) for s in model.basis.states])
    ref = model.basis.index[model.reference]
    return Partition(H, w, ref, scheme), model


def lipkin_partition(N=4, eps=1.0, V=0.2, scheme="one_body"):
    """The Lipkin model of chapters 4, 6 and 7, with W = 0."""
    model = hfm.LipkinHF(N=N, eps=eps, V=V)
    H = model.matrix()
    w = np.zeros(len(model.states))
    for i, s in enumerate(model.states):
        up = sum(1 for p in range(N) if (s >> (N + p)) & 1)
        down = sum(1 for p in range(N) if (s >> p) & 1)
        w[i] = 0.5 * eps * (up - down)
    ref = model.index[model.reference]
    return Partition(H, w, ref, scheme), model


def hubbard_partition(sites=6, n_up=3, n_down=3, t=1.0, U=2.0,
                      scheme="one_body"):
    """The Hubbard ring of chapters 4 and 5, in the momentum basis."""
    model = fci.HubbardFCI(sites=sites, n_up=n_up, n_down=n_down, t=t, U=U)
    H = model.matrix()
    w = np.array([sum(model.eps[k] for k in range(sites) if (u >> k) & 1)
                  + sum(model.eps[k] for k in range(sites) if (d >> k) & 1)
                  for (u, d) in model.states])
    ref = model.index[model.reference]
    return Partition(H, w, ref, scheme), model


def pairing_ph_partition(levels=4, particles=4, g=1.0, f=0.0, xi=1.0,
                         scheme="one_body"):
    """The pairing plus particle-hole model of chapter 7."""
    model = rpamod.PairingPH(levels=levels, particles=particles,
                             g=g, f=f, xi=xi)
    H = model.matrix()
    w = np.array([sum(xi * (rpamod.level_of(o) - 1)
                      for o in range(2 * levels) if (s >> o) & 1)
                  for s in model.states])
    ref = model.index[model.reference()]
    return Partition(H, w, ref, scheme), model


class IndependentPairing:
    """M identical, non-interacting pairing subsystems.

    Each subsystem has ``levels`` equally spaced levels and holds one pair,
    and the pairing interaction acts only within a subsystem.  This is the
    construction of chapter 5, generalised so that more than two levels are
    available and the third-order energy does not vanish trivially.
    """

    def __init__(self, subsystems=2, levels=3, g=0.5, xi=1.0):
        self.subsystems = subsystems
        self.levels_per = levels
        self.g = g
        self.xi = xi
        self.levels = subsystems * levels
        n_particles = 2 * subsystems
        self.basis = fci.SlaterBasis(2 * self.levels, n_particles)
        ref = 0
        for s in range(subsystems):
            low = s * levels
            ref |= (1 << (2 * low)) | (1 << (2 * low + 1))
        self.reference = ref

    def _subsystem(self, level):
        return level // self.levels_per

    def sp_energy(self, orbital):
        level = orbital // 2
        return self.xi * (level % self.levels_per)

    def matrix(self):
        dim = self.basis.dim
        H = np.zeros((dim, dim))
        for col, state in enumerate(self.basis.states):
            H[col, col] += sum(self.sp_energy(o)
                               for o in range(self.basis.n_orbitals)
                               if (state >> o) & 1)
            for q in range(self.levels):
                for p in range(self.levels):
                    if self._subsystem(p) != self._subsystem(q):
                        continue
                    ops = [(2 * p, True), (2 * p + 1, True),
                           (2 * q + 1, False), (2 * q, False)]
                    sign, new = fci.apply_string(state, ops)
                    if sign:
                        H[self.basis.index[new], col] += -0.5 * self.g * sign
        return H

    def partition(self, scheme="one_body"):
        H = self.matrix()
        w = np.array([sum(self.sp_energy(o)
                          for o in range(self.basis.n_orbitals)
                          if (s >> o) & 1) for s in self.basis.states])
        return Partition(H, w, self.basis.index[self.reference], scheme)


def copies_partition(g=0.5, xi=1.0, subsystems=2, scheme="one_body"):
    """Non-interacting copies of a two-level pairing system, chapter 5."""
    model = fci.NonInteractingCopies(g=g, xi=xi, subsystems=subsystems)
    H = model.matrix()
    w = np.array([sum(model._sp_energy(o)
                      for o in range(model.basis.n_orbitals) if (s >> o) & 1)
                  for s in model.basis.states])
    ref = model.basis.index[model.reference]
    return Partition(H, w, ref, scheme), model


# ---------------------------------------------------------------------------
#  Demonstrations
# ---------------------------------------------------------------------------
def demo_recursion():
    print("=" * 74)
    print("1. The recursion against the explicit expressions")
    print("=" * 74)
    print("The series can be generated by a recursion or written out term by")
    print("term.  They must agree, and the third-order agreement is the")
    print("interesting one, because it is there that the renormalisation")
    print("term first appears.")
    print()
    print(f"{'model':>16s} {'E1':>13s} {'E2':>13s} {'E3 (recursion)':>16s} "
          f"{'E3 (explicit)':>15s}")
    cases = [("pairing", pairing_partition(g=0.5)[0]),
             ("Lipkin", lipkin_partition(V=0.2)[0]),
             ("Hubbard", hubbard_partition(U=2.0)[0]),
             ("pairing + p-h", pairing_ph_partition(g=0.5, f=0.025)[0])]
    for name, part in cases:
        e = rayleigh_schrodinger(part, order=3)
        e1, e2, e3, principal, renorm = rs_explicit(part)
        print(f"{name:>16s} {e[0]:13.8f} {e[1]:13.8f} {e[2]:16.8f} "
              f"{e3:15.8f}")
    print()
    print("The two pieces of the third-order term, for the pairing model at")
    print("g = 0.5:")
    part, _ = pairing_partition(g=0.5)
    e1, e2, e3, principal, renorm = rs_explicit(part)
    print(f"   principal term    sum_mn V_0m V_mn V_n0 / D_m D_n  = "
          f"{principal:12.8f}")
    print(f"   renormalisation   V_00 sum_m V_0m V_m0 / D_m^2     = "
          f"{renorm:12.8f}")
    print(f"   difference        Delta E^(3)                      = "
          f"{e3:12.8f}")
    print()
    print("The renormalisation term is not a small correction here: it is")
    print("larger than the third-order energy itself.  Its role is to cancel")
    print("the unlinked contribution, which is what makes the series size")
    print("extensive -- as section 5 below demonstrates.")


def demo_pairing():
    print("=" * 74)
    print("2. The pairing model")
    print("=" * 74)
    print("Four doubly degenerate levels, four particles, xi = 1.  The")
    print("unperturbed reference energy is W_0 = 2 and the first-order energy")
    print("is -g, so E_ref = 2 - g, which is the Hartree-Fock energy of")
    print("chapter 6: the mean field does nothing for this interaction.")
    print()
    print(f"{'g':>6s} {'E_ref':>10s} {'+E2':>12s} {'+E3':>12s} "
          f"{'FCI':>12s} {'CID':>12s} {'HF+RPA':>12s}")
    fock = rpamod.FockSpace(4)
    for g in (0.25, 0.5, 1.0, 1.5, 2.0):
        part, model = pairing_partition(g=g)
        e = rayleigh_schrodinger(part, order=3)
        ref = part.reference_energy
        exact = part.exact()
        c = model.energies(2)[0]
        r = rpamod.tda_rpa(fock, 4, g, 0.0)
        print(f"{g:6.2f} {ref:10.5f} {ref + e[1]:12.8f} "
              f"{ref + e[1] + e[2]:12.8f} {exact:12.8f} {c:12.8f} "
              f"{r['hf'] + r['ecorr']:12.8f}")
    print()
    print("Second order already recovers most of the correlation energy and")
    print("third order improves on it, but the series is not variational:")
    print("nothing forbids it from crossing the exact answer, and at g = 2")
    print("it does.  Compare with CID, which is variational and therefore")
    print("always above, and with RPA, which sums a particular class of")
    print("contributions to all orders.")


def demo_orders():
    print("=" * 74)
    print("3. Going to higher order: does the series converge?")
    print("=" * 74)
    print("The recursion continues to any order, so we can watch the series")
    print("itself rather than guess.  For the pairing model, the size of the")
    print("n-th term:")
    print()
    orders = (2, 5, 10, 20, 40)
    print(f"{'g':>6s} " + " ".join(f"{'|E(' + str(o) + ')|':>11s}"
                                   for o in orders)
          + f" {'through 20':>13s} {'exact':>13s}")
    for g in (0.5, 1.0, 1.5, 2.0, 2.5):
        part, _ = pairing_partition(g=g)
        e = np.array(rayleigh_schrodinger(part, order=41))
        partial = part.reference_energy + np.cumsum(e[1:])
        row = " ".join(f"{abs(e[o - 1]):11.2e}" for o in orders)
        print(f"{g:6.2f} {row} {partial[18]:13.7f} {part.exact():13.7f}")
    print()
    print("At g = 0.5 and g = 1 the terms fall away steadily and the partial")
    print("sums reproduce the exact energy to every digit shown: the series")
    print("converges.  At g = 2 and beyond the terms grow without limit --")
    print("by ten orders of magnitude between the tenth and the fortieth --")
    print("and the partial sums are meaningless.  Somewhere between g = 1 and")
    print("g = 2 lies the radius of convergence, and g = 1.5 sits close to")
    print("it: the terms there decrease so slowly that no finite number of")
    print("them settles the question.")
    print()
    print("This is worth taking seriously.  Perturbation theory is an")
    print("expansion about the reference determinant, and once the true")
    print("ground state has stopped resembling it the expansion has nothing")
    print("to say -- no amount of further work at higher order helps, and")
    print("the divergence is not visible from the first few terms.  At")
    print("g = 1.5, second and third order look perfectly reasonable:")
    part, _ = pairing_partition(g=1.5)
    e = rayleigh_schrodinger(part, order=3)
    ref = part.reference_energy
    print(f"   E_ref = {ref:.5f},  through second = {ref + e[1]:.5f},")
    print(f"   through third = {ref + e[1] + e[2]:.5f},  "
          f"exact = {part.exact():.5f}.")
    print("Nothing in those three numbers warns that the series behind them")
    print("may not converge.  This is the same breakdown that made the mean")
    print("field fail in chapter 6 and the truncated configuration")
    print("interaction deteriorate in chapter 5, seen from a third direction.")


def demo_lipkin():
    print("=" * 74)
    print("4. The Lipkin model")
    print("=" * 74)
    print("N = 4, eps = 1, W = 0.  The interaction changes J_z by two units,")
    print("so the first-order energy vanishes and the reference energy is the")
    print("unperturbed -N eps / 2 = -2.  The RPA result of chapter 7 is")
    print("available in closed form, w = eps sqrt(1 - chi^2), which gives a")
    print("correlation energy to compare against.")
    print()
    print(f"{'chi':>6s} {'E_ref':>9s} {'+E2':>12s} {'+E3':>12s} "
          f"{'exact':>12s} {'RPA':>12s}")
    for chi in (0.25, 0.5, 0.75, 0.9, 1.0):
        V = chi / 3.0
        part, model = lipkin_partition(N=4, eps=1.0, V=V)
        e = rayleigh_schrodinger(part, order=3)
        ref = part.reference_energy
        exact = part.exact()
        # RPA correlation energy: (1/2)(sum omega - Tr A) with the analytic
        # Lipkin blocks of chapters 6 and 7
        A, B = rpamod._lipkin_blocks(N=4, eps=1.0, V=V)
        roots, n_imag = rpamod.solve_rpa(A, B)
        e_rpa = (ref + rpamod.correlation_energy(roots, A)
                 if n_imag == 0 else np.nan)
        print(f"{chi:6.2f} {ref:9.5f} {ref + e[1]:12.8f} "
              f"{ref + e[1] + e[2]:12.8f} {exact:12.8f} {e_rpa:12.8f}")
    print()
    print("Second-order perturbation theory for this model is available in")
    print("closed form.  The interaction connects the reference only to the")
    print("state with two particles lifted, at an excitation energy 2 eps,")
    print("with the matrix element (V/2) sqrt(2 N (N-1)), so that")
    print("   Delta E^(2) = -N(N-1) V^2 / (4 eps),")
    print("which the program checks:")
    print(f"{'chi':>6s} {'E2 (numerical)':>17s} {'E2 (closed form)':>18s}")
    for chi in (0.25, 0.5, 0.75, 1.0):
        V = chi / 3.0
        part, _ = lipkin_partition(N=4, eps=1.0, V=V)
        e = rayleigh_schrodinger(part, order=2)
        closed = -4.0 * 3.0 * V * V / 4.0
        print(f"{chi:6.2f} {e[1]:17.10f} {closed:18.10f}")
    print()
    print("Note where perturbation theory and RPA part company.  RPA sums the")
    print("same 2p-2h correlations to all orders and collapses at chi = 1,")
    print("announcing the mean-field instability of chapter 6.  Perturbation")
    print("theory produces a finite number at chi = 1 and gives no warning")
    print("whatever that anything has gone wrong.")


def demo_size_extensivity():
    print("=" * 74)
    print("5. Size extensivity: Rayleigh-Schrodinger against Brillouin-Wigner")
    print("=" * 74)
    print("Two identical, non-interacting copies of a two-level pairing")
    print("system, the construction of chapter 5.  Any acceptable method must")
    print("give exactly twice the energy of one subsystem.")
    print()
    print("Each subsystem has three levels and one pair, so that the")
    print("third-order energy does not vanish trivially.")
    print()
    for g in (0.25, 0.5, 1.0):
        one = IndependentPairing(subsystems=1, levels=3, g=g).partition()
        two = IndependentPairing(subsystems=2, levels=3, g=g).partition()
        e_one = rayleigh_schrodinger(one, order=4)
        e_two = rayleigh_schrodinger(two, order=4)
        print(f"g = {g}:")
        print(f"   {'order':>8s} {'2 x one':>14s} {'two copies':>14s} "
              f"{'error':>11s}")
        for k, label in ((0, "first"), (1, "second"), (2, "third"),
                         (3, "fourth")):
            print(f"   {label:>8s} {2 * e_one[k]:14.9f} {e_two[k]:14.9f} "
                  f"{e_two[k] - 2 * e_one[k]:11.2e}")
        bw1, _ = brillouin_wigner(one, order=2)
        bw2, _ = brillouin_wigner(two, order=2)
        print(f"   {'BW(2)':>8s} {2 * bw1:14.9f} {bw2:14.9f} "
              f"{bw2 - 2 * bw1:11.2e}")
        print()
    print("Rayleigh-Schrodinger is exact at every order, to machine")
    print("precision.  This is the linked-diagram theorem in action: the")
    print("renormalisation term of section 1 is precisely what cancels the")
    print("unlinked contribution that would otherwise scale as the square of")
    print("the system size.  Brillouin-Wigner, which has no such term, fails,")
    print("and the failure grows with the coupling.  This is the same defect")
    print("that made truncated configuration interaction unusable for")
    print("extended systems in chapter 5, and it is the reason Brillouin-")
    print("Wigner theory is not used for many-body problems.")


def demo_brillouin_wigner():
    print("=" * 74)
    print("6. Brillouin-Wigner, and its exact resummation")
    print("=" * 74)
    print("Brillouin-Wigner puts the exact energy in the denominator, so the")
    print("equation must be solved self-consistently.  Its full resummation")
    print("   Delta E = <Phi_0| V + V Q [E - H_0 - Q V Q]^(-1) Q V |Phi_0>")
    print("is not an approximation at all, and must reproduce the exact")
    print("energy.  For the pairing model:")
    print()
    print(f"{'g':>6s} {'BW(2)':>13s} {'BW(3)':>13s} {'BW exact':>13s} "
          f"{'FCI':>13s} {'iterations':>11s}")
    for g in (0.25, 0.5, 1.0, 1.5, 2.0):
        part, _ = pairing_partition(g=g)
        b2, _ = brillouin_wigner(part, order=2)
        b3, _ = brillouin_wigner(part, order=3)
        bx, iterations = brillouin_wigner_exact(part)
        w0 = part.w0
        print(f"{g:6.2f} {w0 + b2:13.8f} {w0 + b3:13.8f} {w0 + bx:13.8f} "
              f"{part.exact():13.8f} {iterations:11d}")
    print()
    print("The last two columns agree to eight digits, as they must.  This")
    print("is worth pausing on: Brillouin-Wigner theory, resummed, is simply")
    print("a rewriting of the Schrodinger equation, exactly as the text says.")
    print("Its truncations are easy to write down and converge quickly for a")
    print("single system -- but they are not size extensive, and that is")
    print("fatal.")


def demo_hubbard():
    print("=" * 74)
    print("7. The Hubbard model")
    print("=" * 74)
    print("Six sites at half filling in the momentum basis, where the")
    print("plane-wave determinant is the Hartree-Fock solution and the")
    print("first-order energy is the Hartree shift U N_up N_dn / L.")
    print()
    print(f"{'U/t':>6s} {'E_ref':>10s} {'+E2':>12s} {'+E3':>12s} "
          f"{'+E4':>12s} {'FCI':>12s} {'CID':>12s}")
    for U in (1.0, 2.0, 4.0, 8.0):
        part, model = hubbard_partition(U=U)
        e = rayleigh_schrodinger(part, order=4)
        ref, exact = part.reference_energy, part.exact()
        print(f"{U:6.1f} {ref:10.5f} {ref + e[1]:12.8f} "
              f"{ref + e[1] + e[2]:12.8f} {ref + sum(e[1:]):12.8f} "
              f"{exact:12.8f} {model.energies(2)[0]:12.8f}")
    print()
    print("Two things stand out.  First, the third-order energy vanishes")
    print("identically at this filling -- the columns +E2 and +E3 are equal")
    print("to every digit, for every U.  That is special to the half-filled")
    print("ring with a momentum-independent interaction and is not a general")
    print("feature; the pairing model of section 2 has a perfectly good")
    print("third-order term.  Fourth order is not zero, so we have included")
    print("it.")
    print()
    print("Second, the series works beautifully at weak coupling -- at")
    print("U/t = 1 second order is already within two millihartree of the")
    print("exact value -- and collapses at strong coupling.  At U/t = 8 the")
    print("fourth-order term overshoots the exact energy by more than a")
    print("factor of two.  The reference determinant has stopped being a")
    print("good starting point, which is the strong-correlation regime of")
    print("chapter 5 seen through the perturbation series.")


def demo_pairing_ph():
    print("=" * 74)
    print("8. The pairing plus particle-hole model of chapter 7")
    print("=" * 74)
    print("Here the particle-hole term breaks pairs, so the reference does")
    print("couple to singles and the second-order energy picks up a 1p-1h")
    print("contribution as well as the 2p-2h one.  We separate them.")
    print()
    print(f"{'g':>6s} {'f':>7s} {'E_ref':>10s} {'E2(1p1h)':>12s} "
          f"{'E2(2p2h)':>12s} {'+E2':>12s} {'+E3':>12s} {'FCI':>12s}")
    for g, f in ((0.5, 0.025), (0.7, 0.05), (1.0, 0.05), (1.0, 0.5)):
        part, model = pairing_ph_partition(g=g, f=f)
        e = rayleigh_schrodinger(part, order=3)
        ref, exact = part.reference_energy, part.exact()
        # split the second-order sum by excitation level
        levels = np.array([bin(s & ~model.reference()).count("1")
                           for s in model.states])
        v0 = part.V[part.reference]
        contributions = v0 * part.resolvent * v0
        e2_1p1h = float(contributions[levels == 1].sum())
        e2_2p2h = float(contributions[levels == 2].sum())
        print(f"{g:6.2f} {f:7.3f} {ref:10.5f} {e2_1p1h:12.8f} "
              f"{e2_2p2h:12.8f} {ref + e[1]:12.8f} "
              f"{ref + e[1] + e[2]:12.8f} {exact:12.8f}")
    print()
    print("The singles contribution is small but not zero, and it would")
    print("vanish identically in a Hartree-Fock basis by Brillouin's theorem")
    print("-- which is exactly why one works in that basis.  For the three")
    print("weakly coupled rows the series behaves well, third order sitting")
    print("within a few parts in a thousand of the exact answer.  The last")
    print("row is the interesting one: with f = 0.5 g the particle-hole term")
    print("is strong, and third order overshoots the exact energy by 0.56.")
    print("Chapter 7 found RPA overshooting the same row in the same")
    print("direction, -1.73461 against -1.69174, but by only 0.04.  Summing")
    print("a restricted class of contributions to all orders is, here, far")
    print("safer than summing all of them to third order.")


def demo_partitions():
    print("=" * 74)
    print("9. Does the partition matter?")
    print("=" * 74)
    print("Nothing forced our choice of H_0.  Taking the whole diagonal of H")
    print("instead of the one-body part gives the Epstein-Nesbet partition,")
    print("in which the first-order energy vanishes by construction and the")
    print("denominators contain the diagonal of the interaction as well.")
    print()
    print("For three of our four models the two partitions give identical")
    print("results, and it is worth seeing why: the diagonal of V is the")
    print("same on every determinant the reference can reach, so the two")
    print("choices of H_0 differ by a constant, which cancels in every")
    print("energy denominator.")
    print()
    print(f"{'model':>14s} {'spread of diag(V)':>19s}")
    for name, part in (("pairing", pairing_partition(g=1.0)[0]),
                       ("Lipkin", lipkin_partition(V=0.3)[0]),
                       ("Hubbard", hubbard_partition(U=4.0)[0]),
                       ("pairing + p-h", pairing_ph_partition(g=1.0,
                                                              f=0.5)[0])):
        print(f"{name:>14s} {np.ptp(np.diag(part.V)):19.6f}")
    print()
    print("Only the pairing plus particle-hole model has a genuinely varying")
    print("diagonal, because the particle-hole term contributes -f per")
    print("complete pair and the number of complete pairs differs from one")
    print("determinant to the next.  There the two partitions do disagree:")
    print()
    print(f"{'g':>5s} {'f':>6s} {'one-body: +E2':>15s} {'+E3':>12s} "
          f"{'E-N: +E2':>12s} {'+E3':>12s} {'FCI':>12s}")
    for g, f in ((0.5, 0.25), (1.0, 0.5), (1.5, 0.75)):
        a, _ = pairing_ph_partition(g=g, f=f, scheme="one_body")
        b, _ = pairing_ph_partition(g=g, f=f, scheme="diagonal")
        ea = rayleigh_schrodinger(a, order=3)
        eb = rayleigh_schrodinger(b, order=3)
        ra, rb = a.reference_energy, b.reference_energy
        print(f"{g:5.2f} {f:6.2f} {ra + ea[1]:15.8f} "
              f"{ra + ea[1] + ea[2]:12.8f} {rb + eb[1]:12.8f} "
              f"{rb + eb[1] + eb[2]:12.8f} {a.exact():12.8f}")
    print()
    print("Both partitions sum to the same exact answer, but at any finite")
    print("order they disagree, and neither is uniformly better: at second")
    print("order Epstein-Nesbet wins the last row and loses the first two,")
    print("and at third order the two are almost indistinguishable and both")
    print("are very poor.  There is no theorem saying one partition is")
    print("better than another.  The choice is part of the approximation, and")
    print("quoting a perturbative number without saying which partition")
    print("produced it is meaningless.")


def demo_comparison():
    print("=" * 74)
    print("10. Everything against everything")
    print("=" * 74)
    print("The pairing model with four levels and four particles, the one")
    print("system every chapter has now treated.")
    print()
    print(f"{'g':>6s} {'HF':>10s} {'MBPT2':>11s} {'MBPT3':>11s} "
          f"{'CID':>11s} {'HF+RPA':>11s} {'FCI':>11s}")
    fock = rpamod.FockSpace(4)
    rows = []
    for g in (0.25, 0.5, 1.0, 1.5, 2.0):
        part, model = pairing_partition(g=g)
        e = rayleigh_schrodinger(part, order=3)
        ref, exact = part.reference_energy, part.exact()
        r = rpamod.tda_rpa(fock, 4, g, 0.0)
        row = (g, ref, ref + e[1], ref + e[1] + e[2], model.energies(2)[0],
               r["hf"] + r["ecorr"], exact)
        rows.append(row)
        print(f"{g:6.2f} {ref:10.5f} {row[2]:11.6f} {row[3]:11.6f} "
              f"{row[4]:11.6f} {row[5]:11.6f} {exact:11.6f}")
    print()
    print("The same table as errors, which is where the interest lies:")
    print(f"{'g':>6s} {'MBPT2':>11s} {'MBPT3':>11s} {'CID':>11s} "
          f"{'HF+RPA':>11s}")
    for g, ref, m2, m3, cid, rp, exact in rows:
        print(f"{g:6.2f} {m2 - exact:11.2e} {m3 - exact:11.2e} "
              f"{cid - exact:11.2e} {rp - exact:11.2e}")
    print()
    print("Hartree-Fock does nothing at all, since the pairing interaction")
    print("cannot couple the reference to a 1p-1h state.  Beyond that the")
    print("ordering changes with the coupling, and no method wins")
    print("everywhere.  At g = 0.25 third-order perturbation theory is best")
    print("by three orders of magnitude and RPA is the worst of the four.")
    print("At g = 2 the ordering has reversed completely: RPA is best, and")
    print("the perturbation series -- which is diverging, as section 3")
    print("showed -- is the worst.  CID is the only one of the four that is")
    print("variational, so it alone is guaranteed to stay above the exact")
    print("answer, and it alone degrades gracefully.")


def _demo():
    for f in (demo_recursion, demo_pairing, demo_orders, demo_lipkin,
              demo_size_extensivity, demo_brillouin_wigner, demo_hubbard,
              demo_pairing_ph, demo_partitions, demo_comparison):
        f()
        print()


if __name__ == "__main__":
    _demo()
